# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=30, null=True, verbose_name='user_email')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='user_id')),
                ('create_time', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
